### ISSUE TITLE
Chrome won't run the script because of mime type (

### ISSUE THREAD

**Issue by tunght13488** [thedufer/Trello-Bookmarklet-Maker#3]
> Refused to execute script from 'https://raw.github.com/thedufer/Trello-Bookmarklet-Maker/gh-pages/saveToCard.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

This could be the workaround: http://stackoverflow.com/a/18049842/700643

**Comment by thedufer** [comment]
I believe I've fixed the issue with https://github.com/thedufer/Trello-Bookmarklet-Maker/commit/4829fc97c71e50736be70590a88665ce4b7029ee - if it isn't working for you, feel free to re-open.  Keep in mind that you'll have to remake any bookmarklets you have.

Thanks for both the issue and the solution!
